### ISSUE TITLE
Use lowest durability fire striker if more than one present

### ISSUE THREAD

**Issue by SenorSmartyPants** [Remodor/TLD_FireImprovements#3]
With 2 fire strikers in inventory, highest durability one was preselected.

**Comment by Remodor** [comment]
I noticed, that some of the settings don't work as before the 1.95 (I only fixed an exception). Nothing breaking, that's why I released it. If you have multiple matches in the inventory the worst isn't used either.

I could imagine, they are not using the previous method anymore. Will look into it and hopefully find a solution.

Would be nice if you can explain more, what exactly is the problem. The more you describe, the easier it is to fix all occurrences.
When did it happen? What did you light? A fire? A torch? Did you have any other possible firestarters in the inventory?

**Comment by Remodor** [comment]
Nevermind, fixed/ added it. Thanks for the hint. Next release will include it.
